### PR TITLE
Initialize React project

### PR DESCRIPTION
**Pull request by kingjon3377**
This is the result of running `npx create-react-app` (and moving what it creates from a subdirectory to the root of the repository), plus Hound and ESLint configurations so Hound (hopefully) won't spam us.

### CODE REVIEW

**Comment by kingjon3377** [comment]
I've added this repo to my view of all of the bots listed in [the organization settings](https://github.com/organizations/utopia-airlines/settings/oauth_application_policy); I don't see any other way to do CI QA setup ...

**Comment by STOzaki** [comment]
Let me add to. Maybe you have to push again.

**Comment by kingjon3377** [comment]
I force-pushed back a commit and then forward again, and Hound pounced with a dozen or so predictably spurious comments.

**Comment by kingjon3377** [comment]
I did (or at least I hope the `.hound.yml` file this PR includes will actually help); the "force push" I did was going back to the commit before that (since it's not possible to "force push" to *the same* commit).

**Pull request merged**
